[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "dist"

# Force HTTPS and redirect www to non-www
[[redirects]]
  from = "http://abzarbeton.net/*"
  to = "https://abzarbeton.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.abzarbeton.net/*"
  to = "https://abzarbeton.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.abzarbeton.net/*"
  to = "https://abzarbeton.net/:splat"
  status = 301
  force = true

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), camera=(), microphone=(), payment=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.abzarbeton.net https://*.unsplash.com https://*.same-assets.com; font-src 'self'; connect-src 'self'; form-action 'self'; base-uri 'self'; frame-ancestors 'none';"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
